package fileHandler;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;
import java.util.Scanner;

/**
 * 
 * @author General Cleans csc2a projects
 * Cleans the project by deleting files generated by the student' eclipse 
 * replacing them with my settings / data
 */
public class Clean {

	String status = "";

	public Clean(File location) {
		recurse(location);
	}

	private void recurse(File location) {
		for (File file : location.listFiles()) {
			if (file.isDirectory()) {
				if (file.getName().equalsIgnoreCase(".settings"))
					deleletFol(file);
				else if (file.getName().equalsIgnoreCase("bin"))
					deleletFol(file);
				else
					recurse(file);
			} else if ((file.getName().equalsIgnoreCase(".project")) || (file.getName().equals("..classpath")))
				status += "\n" + file.delete();
			else if ((file.getName().contains(".bat"))) {
				Scanner scanner;
				String line = "";
				
				try {
					scanner = new Scanner(new File("docs\\"+file.getName()));
					while (scanner.hasNext()) {
						line += scanner.nextLine() + "\n";
					}
					scanner.close();
					
					writeFile(file, line);
				} catch (FileNotFoundException e) {
					   System.out.println("FileNotFoundException Clean-Recurse()-scanner");
				}
				
			}

		}

	}

	private void deleletFol(File fol) {
		for (File file : fol.listFiles()) {
			status += "\n" + file.delete();
		}
		status += "\n" + fol.delete();
	}

	void writeFile(File file, String text) {
		FileOutputStream fos;
		PrintWriter pw;
		try {
			fos = new FileOutputStream(file, false);
			pw = new PrintWriter(fos);
			pw.write(text);

			pw.flush();
			pw.close();
			
			
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	@Override
	public String toString() {
		return status;
	}
}
